services:
  roundest_nextjs:
    image: roundest_nextjs
    container_name: roundest_app_nextjs
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BACKEND_JAVA: http://app_java:8080
      NEXT_PUBLIC_API_BACKEND_GROOVY: http://app_groovy:8081
      NEXT_PUBLIC_API_BACKEND_KOTLIN: http://app_kotlin:8082
    depends_on:
      - app_java
      - app_groovy
      - app_kotlin

  app_java:
    image: roundest_java
    container_name: roundest_app_java
    ports:
      - "8080:8080"
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATASOURCE_DB: ${DATASOURCE_DB}
      DATASOURCE_HOST: ${DATASOURCE_HOST}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DATASOURCE_PORT: ${DATASOURCE_PORT}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
    depends_on:
      - db

  app_groovy:
    image: roundest_groovy
    container_name: roundest_app_groovy
    ports:
      - "8081:8080"
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATASOURCE_DB: ${DATASOURCE_DB}
      DATASOURCE_HOST: ${DATASOURCE_HOST}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DATASOURCE_PORT: ${DATASOURCE_PORT}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
    depends_on:
      - db

  app_kotlin:
    image: roundest_kotlin
    container_name: roundest_app_kotlin
    ports:
      - "8082:8080"
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATASOURCE_DB: ${DATASOURCE_DB}
      DATASOURCE_HOST: ${DATASOURCE_HOST}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DATASOURCE_PORT: ${DATASOURCE_PORT}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
    depends_on:
      - db

  db:
    image: postgres:14.15-alpine3.21
    container_name: roundest_db
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DB}
    ports:
      - "${DATASOURCE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: